# Form implementation generated from reading ui file 'pumps_vacuum.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pumps_vacuum(object):
    def setupUi(self, Pumps_vacuum):
        Pumps_vacuum.setObjectName("Pumps_vacuum")
        Pumps_vacuum.resize(930, 126)
        self.gridLayout_2 = QtWidgets.QGridLayout(Pumps_vacuum)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.led_pump_load_lock = QtWidgets.QLabel(parent=Pumps_vacuum)
        self.led_pump_load_lock.setMinimumSize(QtCore.QSize(50, 50))
        self.led_pump_load_lock.setMaximumSize(QtCore.QSize(50, 50))
        self.led_pump_load_lock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.led_pump_load_lock.setObjectName("led_pump_load_lock")
        self.gridLayout.addWidget(self.led_pump_load_lock, 0, 0, 1, 1)
        self.label_210 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_210.setFont(font)
        self.label_210.setObjectName("label_210")
        self.gridLayout.addWidget(self.label_210, 0, 1, 1, 1)
        self.vacuum_load_lock = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum_load_lock.sizePolicy().hasHeightForWidth())
        self.vacuum_load_lock.setSizePolicy(sizePolicy)
        self.vacuum_load_lock.setMinimumSize(QtCore.QSize(100, 50))
        self.vacuum_load_lock.setStyleSheet("QLCDNumber{\n"
                                            "border: 2px solid yellow;\n"
                                            "border-radius: 10px;\n"
                                            "padding: 0 8px;\n"
                                            "}")
        self.vacuum_load_lock.setObjectName("vacuum_load_lock")
        self.gridLayout.addWidget(self.vacuum_load_lock, 0, 2, 1, 1)
        self.label_211 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_211.setFont(font)
        self.label_211.setObjectName("label_211")
        self.gridLayout.addWidget(self.label_211, 0, 3, 1, 1)
        self.vacuum_buffer = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum_buffer.sizePolicy().hasHeightForWidth())
        self.vacuum_buffer.setSizePolicy(sizePolicy)
        self.vacuum_buffer.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vacuum_buffer.setFont(font)
        self.vacuum_buffer.setStyleSheet("QLCDNumber{\n"
                                         "border: 2px solid blue;\n"
                                         "border-radius: 10px;\n"
                                         "padding: 0 8px;\n"
                                         "}")
        self.vacuum_buffer.setObjectName("vacuum_buffer")
        self.gridLayout.addWidget(self.vacuum_buffer, 0, 4, 1, 1)
        self.label_212 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_212.setFont(font)
        self.label_212.setObjectName("label_212")
        self.gridLayout.addWidget(self.label_212, 0, 5, 1, 1)
        self.vacuum_main = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum_main.sizePolicy().hasHeightForWidth())
        self.vacuum_main.setSizePolicy(sizePolicy)
        self.vacuum_main.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(False)
        self.vacuum_main.setFont(font)
        self.vacuum_main.setStyleSheet("QLCDNumber{\n"
                                       "border: 2px solid green;\n"
                                       "border-radius: 10px;\n"
                                       "padding: 0 8px;\n"
                                       "}")
        self.vacuum_main.setObjectName("vacuum_main")
        self.gridLayout.addWidget(self.vacuum_main, 0, 6, 1, 1)
        self.pump_load_lock_switch = QtWidgets.QPushButton(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pump_load_lock_switch.sizePolicy().hasHeightForWidth())
        self.pump_load_lock_switch.setSizePolicy(sizePolicy)
        self.pump_load_lock_switch.setMinimumSize(QtCore.QSize(0, 25))
        self.pump_load_lock_switch.setStyleSheet("QPushButton{\n"
                                                 "background: rgb(193, 193, 193)\n"
                                                 "}")
        self.pump_load_lock_switch.setObjectName("pump_load_lock_switch")
        self.gridLayout.addWidget(self.pump_load_lock_switch, 1, 0, 1, 1)
        self.label_213 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_213.setFont(font)
        self.label_213.setObjectName("label_213")
        self.gridLayout.addWidget(self.label_213, 1, 1, 1, 1)
        self.vacuum_load_lock_back = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum_load_lock_back.sizePolicy().hasHeightForWidth())
        self.vacuum_load_lock_back.setSizePolicy(sizePolicy)
        self.vacuum_load_lock_back.setMinimumSize(QtCore.QSize(100, 50))
        self.vacuum_load_lock_back.setStyleSheet("QLCDNumber{\n"
                                                 "border: 2px solid yellow;\n"
                                                 "border-radius: 10px;\n"
                                                 "padding: 0 8px;\n"
                                                 "}")
        self.vacuum_load_lock_back.setObjectName("vacuum_load_lock_back")
        self.gridLayout.addWidget(self.vacuum_load_lock_back, 1, 2, 1, 1)
        self.label_214 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_214.setFont(font)
        self.label_214.setObjectName("label_214")
        self.gridLayout.addWidget(self.label_214, 1, 3, 1, 1)
        self.vacuum_buffer_back = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum_buffer_back.sizePolicy().hasHeightForWidth())
        self.vacuum_buffer_back.setSizePolicy(sizePolicy)
        self.vacuum_buffer_back.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vacuum_buffer_back.setFont(font)
        self.vacuum_buffer_back.setStyleSheet("QLCDNumber{\n"
                                              "border: 2px solid blue;\n"
                                              "border-radius: 10px;\n"
                                              "padding: 0 8px;\n"
                                              "}")
        self.vacuum_buffer_back.setObjectName("vacuum_buffer_back")
        self.gridLayout.addWidget(self.vacuum_buffer_back, 1, 4, 1, 1)
        self.label_215 = QtWidgets.QLabel(parent=Pumps_vacuum)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_215.setFont(font)
        self.label_215.setObjectName("label_215")
        self.gridLayout.addWidget(self.label_215, 1, 5, 1, 1)
        self.temp = QtWidgets.QLCDNumber(parent=Pumps_vacuum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp.sizePolicy().hasHeightForWidth())
        self.temp.setSizePolicy(sizePolicy)
        self.temp.setMinimumSize(QtCore.QSize(100, 50))
        self.temp.setStyleSheet("QLCDNumber{\n"
                                "border: 2px solid brown;\n"
                                "border-radius: 10px;\n"
                                "padding: 0 8px;\n"
                                "}")
        self.temp.setObjectName("temp")
        self.gridLayout.addWidget(self.temp, 1, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Pumps_vacuum)
        QtCore.QMetaObject.connectSlotsByName(Pumps_vacuum)

    def retranslateUi(self, Pumps_vacuum):
        _translate = QtCore.QCoreApplication.translate
        Pumps_vacuum.setWindowTitle(_translate("Pumps_vacuum", "Form"))
        self.led_pump_load_lock.setText(_translate("Pumps_vacuum", "pump"))
        self.label_210.setText(_translate("Pumps_vacuum", "Load lock (mBar)"))
        self.label_211.setText(_translate("Pumps_vacuum", "Buffer Chamber (mBar)"))
        self.label_212.setText(_translate("Pumps_vacuum", "Main Chamber (mBar)"))
        self.pump_load_lock_switch.setText(_translate("Pumps_vacuum", "Load Lock Pump"))
        self.label_213.setText(_translate("Pumps_vacuum", "Load Lock Pre(mBar)"))
        self.label_214.setText(_translate("Pumps_vacuum", "Buffer Chamber Pre (mBar)"))
        self.label_215.setText(_translate("Pumps_vacuum", "Temperature (K)"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Pumps_vacuum = QtWidgets.QWidget()
    ui = Ui_Pumps_vacuum()
    ui.setupUi(Pumps_vacuum)
    Pumps_vacuum.show()
    sys.exit(app.exec())
