# Form implementation generated from reading ui file 'gates.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 357)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.diagram = QtWidgets.QLabel(parent=Form)
        self.diagram.setMinimumSize(QtCore.QSize(378, 246))
        self.diagram.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.diagram.setStyleSheet("QWidget{\n"
                                   "border: 2px solid gray;\n"
                                   "background: rgb(255, 255, 255)\n"
                                   "}")
        self.diagram.setText("")
        self.diagram.setObjectName("diagram")
        self.gridLayout.addWidget(self.diagram, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.led_main_chamber = QtWidgets.QLabel(parent=Form)
        self.led_main_chamber.setMinimumSize(QtCore.QSize(50, 50))
        self.led_main_chamber.setMaximumSize(QtCore.QSize(50, 50))
        self.led_main_chamber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.led_main_chamber.setObjectName("led_main_chamber")
        self.horizontalLayout.addWidget(self.led_main_chamber)
        self.led_load_lock = QtWidgets.QLabel(parent=Form)
        self.led_load_lock.setMinimumSize(QtCore.QSize(50, 50))
        self.led_load_lock.setMaximumSize(QtCore.QSize(50, 50))
        self.led_load_lock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.led_load_lock.setObjectName("led_load_lock")
        self.horizontalLayout.addWidget(self.led_load_lock)
        self.led_cryo = QtWidgets.QLabel(parent=Form)
        self.led_cryo.setMinimumSize(QtCore.QSize(50, 50))
        self.led_cryo.setMaximumSize(QtCore.QSize(50, 50))
        self.led_cryo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.led_cryo.setObjectName("led_cryo")
        self.horizontalLayout.addWidget(self.led_cryo)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_chamber_switch = QtWidgets.QPushButton(parent=Form)
        self.main_chamber_switch.setMinimumSize(QtCore.QSize(0, 25))
        self.main_chamber_switch.setStyleSheet("QPushButton{\n"
                                               "background: rgb(193, 193, 193)\n"
                                               "}")
        self.main_chamber_switch.setObjectName("main_chamber_switch")
        self.horizontalLayout_2.addWidget(self.main_chamber_switch)
        self.load_lock_switch = QtWidgets.QPushButton(parent=Form)
        self.load_lock_switch.setMinimumSize(QtCore.QSize(0, 25))
        self.load_lock_switch.setStyleSheet("QPushButton{\n"
                                            "background: rgb(193, 193, 193)\n"
                                            "}")
        self.load_lock_switch.setObjectName("load_lock_switch")
        self.horizontalLayout_2.addWidget(self.load_lock_switch)
        self.cryo_switch = QtWidgets.QPushButton(parent=Form)
        self.cryo_switch.setMinimumSize(QtCore.QSize(0, 25))
        self.cryo_switch.setStyleSheet("QPushButton{\n"
                                       "background: rgb(193, 193, 193)\n"
                                       "}")
        self.cryo_switch.setObjectName("cryo_switch")
        self.horizontalLayout_2.addWidget(self.cryo_switch)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.main_chamber_switch, self.load_lock_switch)
        Form.setTabOrder(self.load_lock_switch, self.cryo_switch)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.led_main_chamber.setText(_translate("Form", "Main"))
        self.led_load_lock.setText(_translate("Form", "Load"))
        self.led_cryo.setText(_translate("Form", "Cryo"))
        self.main_chamber_switch.setText(_translate("Form", "Main Chamber"))
        self.load_lock_switch.setText(_translate("Form", "Load Lock"))
        self.cryo_switch.setText(_translate("Form", "Cryo"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
